/*
 * The dictionary: every word on the site, once, grouped by the unit that
 * teaches it. Its audio is words/audio/<id>.mp3 (tools/tts.mjs) and its
 * picture words/img/<id>.svg (from words/art.mjs, tools/draw.mjs).
 *
 *   Words.add(n, [entries])   the words unit n teaches (each gets taught: n)
 *
 * A unit's vocab.js takes the words it uses with Words.get(id) or
 * Words.list('a b c'), adding its own fields, and builds its phrases and
 * sentences from them. Entry fields are in tools/vocab-fields.mjs; an id
 * is unique on the site (when two words would share one, one gets its
 * tone number: 大 daai6). shared/units.js documents Words.
 */
Words.voice = 'zh-HK-HiuMaanNeural';

// Unit 1 · Sounds & Tones 聲調
Words.add(1, [
  // basics
  { id: 'cantonese', hanzi: '廣東話', jyutping: 'gwong2 dung1 waa2', english: 'Cantonese', img: false,
    note: '話 on its own is waa6. In 廣東話 it changes to waa2.' },
  { id: 'jyutping', hanzi: '粵拼', jyutping: 'jyut6 ping3', english: 'Jyutping', img: false,
    note: 'The spelling system used on this site. Every syllable ends in its tone number.' },
  { id: 'tone', hanzi: '聲調', jyutping: 'sing1 diu6', english: 'tone', img: false },
  // sets: the six-tone sets are read by WanLung (a man's voice). The
  // site's voice, HiuMaan, says tones 2 and 5 almost alike (婦 fu5 rises
  // like 苦 fu2) and 3 and 6 close together; a native speaker heard it, and
  // audio-lang-tools measured it. Telling HiuMaan the tones with phonemes
  // doesn't help: it is how the voice speaks. WanLung keeps all six apart
  // best of the Azure voices.
  { id: 'si1', hanzi: '詩', jyutping: 'si1', english: 'poem', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'si2', hanzi: '史', jyutping: 'si2', english: 'history', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'si3', hanzi: '試', jyutping: 'si3', english: 'to try', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'si4', hanzi: '時', jyutping: 'si4', english: 'time', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'si5', hanzi: '市', jyutping: 'si5', english: 'market', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'si6', hanzi: '事', jyutping: 'si6', english: 'matter, thing', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fu1', hanzi: '夫', jyutping: 'fu1', english: 'husband', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fu2', hanzi: '苦', jyutping: 'fu2', english: 'bitter', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fu3', hanzi: '富', jyutping: 'fu3', english: 'rich', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fu4', hanzi: '扶', jyutping: 'fu4', english: 'to help up', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fu5', hanzi: '婦', jyutping: 'fu5', english: 'woman', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fu6', hanzi: '父', jyutping: 'fu6', english: 'father', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fan1', hanzi: '分', jyutping: 'fan1', english: 'to share out', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fan2', hanzi: '粉', jyutping: 'fan2', english: 'powder, rice noodles', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fan3', hanzi: '瞓', jyutping: 'fan3', english: 'to sleep', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fan4', hanzi: '墳', jyutping: 'fan4', english: 'grave', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fan5', hanzi: '憤', jyutping: 'fan5', english: 'anger', img: false, voice: 'zh-HK-WanLungNeural' },
  { id: 'fan6', hanzi: '份', jyutping: 'fan6', english: 'portion, share', img: false, voice: 'zh-HK-WanLungNeural' },
  // spelling
  { id: 'fish', hanzi: '魚', jyutping: 'jyu4', english: 'fish',
    note: 'j sounds like English "y". yu is "ee" said with rounded lips, like German ü.' },
  { id: 'cow', hanzi: '牛', jyutping: 'ngau4', english: 'cow',
    note: 'ng can start a syllable: the sound at the end of "sing", moved to the front.' },
  { id: 'ng', hanzi: '吳', jyutping: 'ng4', english: 'Ng (a family name)', img: false,
    note: 'ng can even be a whole syllable, hummed through the nose.' },
  { id: 'congee', hanzi: '粥', jyutping: 'zuk1', english: 'congee (rice porridge)',
    note: 'z is like "dz" with no puff of air. A final k is stopped, not said out loud.' },
  { id: 'car', hanzi: '車', jyutping: 'ce1', english: 'car',
    note: 'c is like "ts" or "ch" with a puff of air.' },
  { id: 'water', hanzi: '水', jyutping: 'seoi2', english: 'water',
    note: 'eoi starts like "er" with rounded lips and slides to "ee".' },
  { id: 'hong-kong', hanzi: '香港', jyutping: 'hoeng1 gong2', english: 'Hong Kong', img: false,
    note: 'oe is like the "ur" in "fur" with rounded lips.' },
  { id: 'chicken', hanzi: '雞', jyutping: 'gai1', english: 'chicken',
    note: 'A single a is short, like the "u" in "but".' },
  { id: 'street', hanzi: '街', jyutping: 'gaai1', english: 'street', img: false,
    note: 'aa is long, like "ah". 雞 gai1 and 街 gaai1 differ only in vowel length.' },
  // praise
  { id: 'hou-lek', hanzi: '好叻呀！', jyutping: 'hou2 lek1 aa3', english: 'Well done! (literally "so clever!")', img: false,
    note: '叻 lek1 means clever or good at something. You\'ll hear this in the games when you get a whole level right.' },
]);

// Unit 2 · Greetings 打招呼
Words.add(2, [
  // greetings
  { id: 'hello', hanzi: '你好', jyutping: 'nei5 hou2', english: 'hello', img: false,
    note: 'Polite, a little formal. Friends often just say "hi" or "hello" in English.' },
  { id: 'good-morning', hanzi: '早晨', jyutping: 'zou2 san4', english: 'good morning',
    note: 'Used until about noon. There is no everyday "good afternoon".' },
  { id: 'good-night', hanzi: '早唞', jyutping: 'zou2 tau2', english: 'good night',
    note: 'Only when someone is going to sleep, never as "good evening".' },
  { id: 'bye', hanzi: '拜拜', jyutping: 'baai1 baai3', english: 'bye-bye',
    note: 'From English "bye-bye". What most people say.' },
  { id: 'goodbye', hanzi: '再見', jyutping: 'zoi3 gin3', english: 'goodbye', img: false,
    note: 'Literally "see again". More formal than 拜拜.' },
  // howAreYou
  { id: 'how-are-you', hanzi: '你好嗎？', jyutping: 'nei5 hou2 maa3', english: 'how are you?', img: false,
    note: 'The textbook question. Correct, but it sounds stiff.' },
  { id: 'how-lately', hanzi: '最近點呀？', jyutping: 'zeoi3 gan6 dim2 aa3', english: 'how have you been?', img: false,
    note: 'What people really say. 點 means "how", and 呀 makes it friendly.' },
  { id: 'pretty-good', hanzi: '幾好', jyutping: 'gei2 hou2', english: 'pretty good', img: false },
  { id: 'so-so', hanzi: '麻麻哋', jyutping: 'maa4 maa2 dei2', english: 'so-so', img: false },
  { id: 'long-time', hanzi: '好耐冇見', jyutping: 'hou2 noi6 mou5 gin3', english: 'long time no see', img: false },
  { id: 'eaten-yet', hanzi: '食咗飯未呀？', jyutping: 'sik6 zo2 faan6 mei6 aa3', english: 'have you eaten yet?', img: false,
    note: 'A friendly greeting, not an invitation. Just answer and chat on.' },
  { id: 'eaten', hanzi: '食咗喇', jyutping: 'sik6 zo2 laa3', english: 'I have eaten', img: false },
  // polite
  { id: 'm-goi', hanzi: '唔該', jyutping: 'm4 goi1', english: 'thank you (for a service); excuse me',
    note: 'For a service or a favour, and to get someone\'s attention.' },
  { id: 'm-goi-saai', hanzi: '唔該晒', jyutping: 'm4 goi1 saai3', english: 'thanks a lot', img: false,
    note: '晒 means "all": thanks for everything you did.' },
  { id: 'thanks', hanzi: '多謝', jyutping: 'do1 ze6', english: 'thank you (for a gift)',
    note: 'For a gift or a compliment.' },
  { id: 'no-need', hanzi: '唔使', jyutping: 'm4 sai2', english: 'no need; you\'re welcome', img: false,
    note: 'The answer to 唔該: "no need to thank me".' },
  { id: 'welcome', hanzi: '唔使客氣', jyutping: 'm4 sai2 haak3 hei3', english: 'you\'re welcome', img: false,
    note: 'The answer to 多謝: "no need to be polite".' },
  { id: 'sorry', hanzi: '對唔住', jyutping: 'deoi3 m4 zyu6', english: 'sorry',
    note: 'A real apology, when you did something wrong.' },
  { id: 'excuse-me', hanzi: '唔好意思', jyutping: 'm4 hou2 ji3 si3', english: 'excuse me; sorry (small)', img: false,
    note: 'For small things: a bump, being late, asking a stranger.' },
  { id: 'never-mind', hanzi: '唔緊要', jyutping: 'm4 gan2 jiu3', english: 'never mind; it\'s OK', img: false },
  { id: 'no-problem', hanzi: '冇問題', jyutping: 'mou5 man6 tai4', english: 'no problem', img: false },
]);

// Unit 3 · Me & You 我同你
Words.add(3, [
  // people
  { id: 'ngo', hanzi: '我', jyutping: 'ngo5', english: 'I; me' },
  { id: 'nei', hanzi: '你', jyutping: 'nei5', english: 'you' },
  { id: 'keoi', hanzi: '佢', jyutping: 'keoi5', english: 'he; she; it',
    note: 'One word for he, she and it.' },
  { id: 'ngo-dei', hanzi: '我哋', jyutping: 'ngo5 dei6', english: 'we; us',
    note: 'Add 哋 to make any of the three plural.' },
  { id: 'nei-dei', hanzi: '你哋', jyutping: 'nei5 dei6', english: 'you (more than one)' },
  { id: 'keoi-dei', hanzi: '佢哋', jyutping: 'keoi5 dei6', english: 'they; them' },
  // words
  { id: 'hai', hanzi: '係', jyutping: 'hai6', english: 'am; is; are', img: false,
    note: 'Links two nouns: 我係學生, I am a student. Never before an adjective.' },
  { id: 'm', hanzi: '唔', jyutping: 'm4', english: 'not', img: false,
    note: 'Goes right before the verb: 唔係, 唔識.' },
  { id: 'giu', hanzi: '叫', jyutping: 'giu3', english: 'to be called', img: false },
  { id: 'meng', hanzi: '名', jyutping: 'meng2', english: 'name', img: false, phoneme: true,
    note: 'meng4 in writing, but meng2 when you ask a name.' },
  { id: 'sik', hanzi: '識', jyutping: 'sik1', english: 'to know how to; can', img: false,
    note: 'For skills you have learned, like a language.' },
  { id: 'gong', hanzi: '講', jyutping: 'gong2', english: 'to speak; to say', img: false },
  { id: 'dou', hanzi: '都', jyutping: 'dou1', english: 'also; too', img: false,
    note: 'Goes before the verb: 我都係, me too.' },
  { id: 'aa-ming', hanzi: '阿明', jyutping: 'aa3 ming4', english: 'Ah Ming (a name)', img: false,
    note: '阿 before one syllable of a name is friendly, like a nickname.' },
  // things
  { id: 'lou-si', hanzi: '老師', jyutping: 'lou5 si1', english: 'teacher' },
  { id: 'hok-saang', hanzi: '學生', jyutping: 'hok6 saang1', english: 'student' },
  { id: 'pang-jau', hanzi: '朋友', jyutping: 'pang4 jau5', english: 'friend' },
  { id: 'hoeng-gong-jan', hanzi: '香港人', jyutping: 'hoeng1 gong2 jan4', english: 'Hongkonger',
    note: '人 after a place makes a person from there.' },
  { id: 'jing-gwok-jan', hanzi: '英國人', jyutping: 'jing1 gwok3 jan4', english: 'British person', img: false },
  { id: 'mei-gwok-jan', hanzi: '美國人', jyutping: 'mei5 gwok3 jan4', english: 'American', img: false },
  { id: 'jing-man', hanzi: '英文', jyutping: 'jing1 man2', english: 'English', img: false, phoneme: true },
  // asking
  { id: 'bin-go', hanzi: '邊個', jyutping: 'bin1 go3', english: 'who', img: false },
  { id: 'mat-je', hanzi: '乜嘢', jyutping: 'mat1 je5', english: 'what', img: false },
  { id: 'maa', hanzi: '嗎', jyutping: 'maa3', english: '(turns a sentence into a yes/no question)', img: false, phoneme: true,
    note: 'Add it to the end of a sentence. Never with 邊個, 乜嘢 or A唔A.' },
  { id: 'aa', hanzi: '呀', jyutping: 'aa3', english: '(softens a question or an answer)', img: false, phoneme: true,
    note: 'Questions without it can sound blunt.' },
  { id: 'ne', hanzi: '呢', jyutping: 'ne1', english: 'and ...? (what about)', img: false, phoneme: true,
    note: 'After a person: 你呢？, and you?' },
  { id: 'siu-siu', hanzi: '少少', jyutping: 'siu2 siu2', english: 'a little', img: false },
  { id: 'hai-mai', hanzi: '係咪', jyutping: 'hai6 mai6', english: 'is it? (short for 係唔係)', img: false,
    note: 'Fast speech squeezes 係唔係 into 係咪. You will hear it everywhere.' },
]);

// Unit 4 · Numbers 數字
Words.add(4, [
  // words
  { id: 'baak', hanzi: '百', jyutping: 'baak3', english: 'hundred', img: false },
  { id: 'cin', hanzi: '千', jyutping: 'cin1', english: 'thousand', img: false },
  { id: 'maan', hanzi: '萬', jyutping: 'maan6', english: 'ten thousand', img: false,
    note: 'Big numbers are counted in 萬s: 100,000 is 十萬, "ten ten-thousands".' },
  { id: 'loeng', hanzi: '兩', jyutping: 'loeng5', english: 'two (of something)', img: false,
    note: 'Before a measure word (兩個) and at the start of 兩百, 兩千, 兩萬.' },
  { id: 'go', hanzi: '個', jyutping: 'go3', english: 'the everyday measure word', img: false,
    note: 'A number needs a measure word before a noun: 三個人, three people. Unit 5 has many more.' },
  { id: 'dai', hanzi: '第', jyutping: 'dai6', english: '-th (makes an ordinal)', img: false,
    note: '第 + number: 第一 first, 第二 second.' },
  { id: 'gei-do', hanzi: '幾多', jyutping: 'gei2 do1', english: 'how many; how much', img: false,
    note: 'Ask 幾多？ for any number. 幾多錢？ asks a price (unit 6).' },
  { id: 'gei-do-go', hanzi: '幾多個？', jyutping: 'gei2 do1 go3', english: 'how many (of them)?', img: false },
]);

// Unit 5 · Measure Words 量詞
Words.add(5, [
  // measures
  { id: 'zek', hanzi: '隻', jyutping: 'zek3', english: 'for animals', img: false,
    note: 'Almost every animal: 一隻貓, 一隻狗. Also one of a pair, like one shoe.' },
  { id: 'bun', hanzi: '本', jyutping: 'bun2', english: 'for books', img: false,
    note: 'Anything bound like a book: books, notebooks, magazines.' },
  { id: 'zoeng', hanzi: '張', jyutping: 'zoeng1', english: 'for flat things', img: false,
    note: 'Things with a flat surface: paper, photos, tickets, and tables, chairs and beds.' },
  { id: 'tiu', hanzi: '條', jyutping: 'tiu4', english: 'for long, thin things', img: false,
    note: 'Long and bendy: fish, snakes, roads, trousers, rivers.' },
  { id: 'zi', hanzi: '枝', jyutping: 'zi1', english: 'for sticks', img: false,
    note: 'Long and stiff: pens, flowers, bottles.' },
  { id: 'gaa', hanzi: '架', jyutping: 'gaa3', english: 'for vehicles and machines', img: false,
    note: 'Cars, planes, bikes, and machines like cameras.' },
  { id: 'gin', hanzi: '件', jyutping: 'gin6', english: 'for tops and pieces', img: false,
    note: 'Clothes for the top half (a shirt, a jacket) and pieces, like a slice of cake.' },
  { id: 'bui', hanzi: '杯', jyutping: 'bui1', english: 'a cup of', dish: 'cup', img: false,
    note: 'A container can be a measure word: 一杯茶, a cup of tea.' },
  { id: 'wun', hanzi: '碗', jyutping: 'wun2', english: 'a bowl of', dish: 'bowl', img: false,
    note: 'For what comes in a bowl: 一碗飯, a bowl of rice.' },
  { id: 'deoi', hanzi: '對', jyutping: 'deoi3', english: 'a pair of', img: false,
    note: 'Things that come in twos: shoes, socks, chopsticks.' },
  // things
  { id: 'apple', hanzi: '蘋果', jyutping: 'ping4 gwo2', english: 'apple', measure: 'go', counted: ['an apple', 'apples'] },
  { id: 'ball', hanzi: '波', jyutping: 'bo1', english: 'ball', measure: 'go',
    note: 'From the English "ball".' },
  { id: 'cat', hanzi: '貓', jyutping: 'maau1', english: 'cat', measure: 'zek' },
  { id: 'dog', hanzi: '狗', jyutping: 'gau2', english: 'dog', measure: 'zek' },
  { id: 'book', hanzi: '書', jyutping: 'syu1', english: 'book', measure: 'bun' },
  { id: 'paper', hanzi: '紙', jyutping: 'zi2', english: 'paper', measure: 'zoeng', counted: ['a sheet of paper', 'sheets of paper'] },
  { id: 'table', hanzi: '枱', jyutping: 'toi2', english: 'table', measure: 'zoeng', phoneme: true,
    note: 'Usually toi2. A table counts as flat.' },
  { id: 'trousers', hanzi: '褲', jyutping: 'fu3', english: 'trousers', measure: 'tiu', counted: ['a pair of trousers', 'pairs of trousers'],
    note: 'One 條, not a pair: long legs make trousers long and thin.' },
  { id: 'pen', hanzi: '筆', jyutping: 'bat1', english: 'pen', measure: 'zi' },
  { id: 'flower', hanzi: '花', jyutping: 'faa1', english: 'flower', measure: 'zi',
    note: 'One flower on its stalk.' },
  { id: 'plane', hanzi: '飛機', jyutping: 'fei1 gei1', english: 'plane', measure: 'gaa',
    note: 'Literally "flying machine".' },
  { id: 'shirt', hanzi: '衫', jyutping: 'saam1', english: 'shirt', measure: 'gin',
    note: '衫 is any top: shirt, T-shirt, jumper.' },
  { id: 'cake', hanzi: '蛋糕', jyutping: 'daan6 gou1', english: 'cake', measure: 'gin', counted: ['a piece of cake', 'pieces of cake'],
    note: 'Literally "egg cake". A slice is 一件.' },
  { id: 'tea', hanzi: '茶', jyutping: 'caa4', english: 'tea', measure: 'bui', counted: ['a cup of tea', 'cups of tea'] },
  { id: 'rice', hanzi: '飯', jyutping: 'faan6', english: 'rice', measure: 'wun', counted: ['a bowl of rice', 'bowls of rice'],
    note: 'Cooked rice, and a meal in general: 食飯, to eat.' },
  { id: 'noodles', hanzi: '麵', jyutping: 'min6', english: 'noodles', measure: 'wun', counted: ['a bowl of noodles', 'bowls of noodles'] },
  { id: 'shoes', hanzi: '鞋', jyutping: 'haai4', english: 'shoes', measure: 'deoi', counted: ['a pair of shoes', 'pairs of shoes'] },
  { id: 'chopsticks', hanzi: '筷子', jyutping: 'faai3 zi2', english: 'chopsticks', measure: 'deoi', counted: ['a pair of chopsticks', 'pairs of chopsticks'] },
  // words
  { id: 'di', hanzi: '啲', jyutping: 'di1', english: 'some; the (more than one)', img: false,
    note: 'The measure word for more than one, or an amount: 啲書, the books. No number before it.' },
  { id: 'ni', hanzi: '呢', jyutping: 'ni1', english: 'this', img: false, phoneme: true,
    note: 'Before a measure word: 呢隻貓, this cat. Not the ne1 of 你呢？' },
  { id: 'go2', hanzi: '嗰', jyutping: 'go2', english: 'that', img: false,
    note: 'Before a measure word: 嗰本書, that book.' },
  { id: 'jau', hanzi: '有', jyutping: 'jau5', english: 'to have; there is', img: false },
]);

// Unit 6 · Money & Shopping 買嘢
Words.add(6, [
  // money
  { id: 'cin2', hanzi: '錢', jyutping: 'cin2', english: 'money', img: false, phoneme: true,
    note: 'cin4 in writing; everyday speech says cin2, as in 幾多錢.' },
  { id: 'man', hanzi: '蚊', jyutping: 'man1', english: 'dollar', img: false,
    note: 'The spoken word for a dollar. Price tags write $ or 元.' },
  { id: 'hou4', hanzi: '毫', jyutping: 'hou4', english: 'ten cents', img: false,
    note: 'Also 毫子. 五毫 is 50 cents; Hong Kong has no smaller coin.' },
  { id: 'bun3', hanzi: '半', jyutping: 'bun3', english: 'half', img: false,
    note: 'After 蚊 it means 50 cents: 三蚊半, $3.50.' },
  { id: 'zaau', hanzi: '找', jyutping: 'zaau2', english: 'to give change', img: false },
  // words
  { id: 'maai5', hanzi: '買', jyutping: 'maai5', english: 'to buy', img: false,
    note: 'Low rising tone 5. 買嘢 is "to go shopping".' },
  { id: 'maai6', hanzi: '賣', jyutping: 'maai6', english: 'to sell', img: false,
    note: 'Low level tone 6: only the tone tells buy and sell apart.' },
  { id: 'jiu', hanzi: '要', jyutping: 'jiu3', english: 'to want; I\'ll take', img: false,
    note: '我要 is how you ask for something in a shop. 唔要, "don\'t want".' },
  { id: 'peng', hanzi: '平', jyutping: 'peng4', english: 'cheap', img: false, phoneme: true,
    note: 'peng4 in speech; ping4 in words like 和平 (peace).' },
  { id: 'gwai', hanzi: '貴', jyutping: 'gwai3', english: 'expensive', img: false },
  { id: 'hou', hanzi: '好', jyutping: 'hou2', english: 'very; good', img: false,
    note: 'Before an adjective: 好貴, very expensive. An adjective needs no 係.' },
  { id: 'dak', hanzi: '得', jyutping: 'dak1', english: 'OK; can do', img: false,
    note: '得唔得？ asks "is that OK?". Answer 得 (yes) or 唔得 (no).' },
  // things
  { id: 'orange', hanzi: '橙', jyutping: 'caang2', english: 'orange', measure: 'go', counted: ['an orange', 'oranges'] },
  { id: 'egg', hanzi: '雞蛋', jyutping: 'gai1 daan2', english: 'egg', measure: 'zek', counted: ['an egg', 'eggs'], phoneme: true,
    note: '蛋 is daan6, but 雞蛋 changes to daan2. Eggs take 隻.' },
  { id: 'watermelon', hanzi: '西瓜', jyutping: 'sai1 gwaa1', english: 'watermelon', measure: 'go',
    note: 'Literally "western melon".' },
  { id: 'bread', hanzi: '麵包', jyutping: 'min6 baau1', english: 'bread roll', measure: 'go',
    note: '麵包 is any bread; a roll or bun takes 個.' },
]);

// Unit 7 · Dim Sum 點心
Words.add(7, [
  // basics
  { id: 'yum-cha', hanzi: '飲茶', jyutping: 'jam2 caa4', english: 'yum cha (go for dim sum)',
    note: 'Literally "drink tea". The tea comes first, and the dim sum comes with it.' },
  { id: 'dim-sum', hanzi: '點心', jyutping: 'dim2 sam1', english: 'dim sum', img: false,
    note: 'The small dishes you eat at yum cha, usually shared, often in bamboo steamers.' },
  // groups
  { id: 'steamed', hanzi: '蒸', jyutping: 'zing1', english: 'steamed', img: false },
  { id: 'fried', hanzi: '煎炸', jyutping: 'zin1 zaa3', english: 'pan-fried & deep-fried', img: false },
  { id: 'baked', hanzi: '焗', jyutping: 'guk6', english: 'baked', img: false },
  { id: 'sweet', hanzi: '甜', jyutping: 'tim4', english: 'sweet', img: false },
  { id: 'rice-noodles', hanzi: '粥粉麵飯', jyutping: 'zuk1 fan2 min6 faan6', english: 'congee, noodles & rice', img: false,
    note: 'Congee (粥), rice noodles (粉), noodles (麵) and rice (飯): the bigger dishes, on the menu under this heading.' },
  // measures
  { id: 'lung', hanzi: '籠', jyutping: 'lung4', english: 'basket', dish: 'steamer', img: false,
    note: 'For anything that comes in a bamboo steamer: 一籠蝦餃.' },
  { id: 'dip', hanzi: '碟', jyutping: 'dip6', english: 'plate', dish: 'plate', img: false,
    note: 'For anything that comes on a plate: 一碟腸粉.' },
  // items
  { id: 'har-gow', hanzi: '蝦餃', jyutping: 'haa1 gaau2', english: 'shrimp dumpling', measure: 'lung',
    note: 'See-through wrapper with a whole shrimp inside. Chefs are judged by these.' },
  { id: 'siu-mai', hanzi: '燒賣', jyutping: 'siu1 maai2', english: 'pork & shrimp dumpling', measure: 'lung',
    note: 'Open-topped and yellow, with a dot of orange roe on top.' },
  { id: 'char-siu-bao', hanzi: '叉燒包', jyutping: 'caa1 siu1 baau1', english: 'BBQ pork bun', measure: 'lung',
    note: 'A fluffy bun that splits open to show sweet barbecued pork.' },
  { id: 'cheung-fun', hanzi: '腸粉', jyutping: 'coeng2 fan2', english: 'rice noodle roll', measure: 'dip',
    note: 'Silky rolls with sweet soy sauce. 腸 is usually coeng4; here it changes to coeng2.' },
  { id: 'chicken-feet', hanzi: '鳳爪', jyutping: 'fung6 zaau2', english: 'chicken feet', measure: 'lung',
    note: 'Literally "phoenix claws", steamed in black bean sauce.' },
  { id: 'spare-ribs', hanzi: '排骨', jyutping: 'paai4 gwat1', english: 'steamed spare ribs', measure: 'lung',
    note: 'Bite-size ribs with black beans, garlic and chili.' },
  { id: 'lo-mai-gai', hanzi: '糯米雞', jyutping: 'no6 mai5 gai1', english: 'sticky rice in lotus leaf', measure: 'lung',
    note: 'Sticky rice with chicken and mushroom. Unwrap it; the leaf is not eaten.' },
  { id: 'xiao-long-bao', hanzi: '小籠包', jyutping: 'siu2 lung4 baau1', english: 'soup dumpling', measure: 'lung',
    note: 'From Shanghai: a "little basket bun" with hot soup inside. Bite a small hole and sip the soup first.' },
  { id: 'beef-tripe', hanzi: '牛柏葉', jyutping: 'ngau4 paak3 jip6', english: 'beef tripe', measure: 'lung',
    note: 'Steamed with ginger and spring onion. Its thin folds look like leaves (葉). Also written 牛百葉.' },
  { id: 'zaa-loeng', hanzi: '炸兩', jyutping: 'zaa3 loeng2', english: 'fried dough in rice noodle roll', measure: 'dip',
    note: 'A crispy fried dough stick rolled up in 腸粉. 兩 is usually loeng5; here it changes to loeng2.' },
  { id: 'spring-roll', hanzi: '春卷', jyutping: 'ceon1 gyun2', english: 'spring roll', measure: 'dip',
    note: 'Crispy and golden. 春 means spring.' },
  { id: 'turnip-cake', hanzi: '蘿蔔糕', jyutping: 'lo4 baak6 gou1', english: 'turnip cake', measure: 'dip',
    note: 'White radish (蘿蔔) and rice flour, sliced and pan-fried.' },
  { id: 'ham-sui-gok', hanzi: '鹹水角', jyutping: 'haam4 seoi2 gok3', english: 'fried sticky rice dumpling', measure: 'dip',
    note: 'A chewy, slightly sweet sticky-rice shell around savory pork, deep-fried. 角 is also said gok2.' },
  { id: 'char-siu-sou', hanzi: '叉燒酥', jyutping: 'caa1 siu1 sou1', english: 'BBQ pork puff', measure: 'dip',
    note: 'Flaky pastry (酥) around sweet barbecued pork, baked golden.' },
  { id: 'egg-tart', hanzi: '蛋撻', jyutping: 'daan6 taat1', english: 'egg tart', measure: 'dip',
    note: '撻 is borrowed from the English word "tart".' },
  { id: 'lai-wong-bao', hanzi: '流沙包', jyutping: 'lau4 saa1 baau1', english: 'custard lava bun', measure: 'lung',
    note: '"Flowing sand bun": salted egg-yolk custard runs out when you bite it.' },
  { id: 'ma-lai-go', hanzi: '馬拉糕', jyutping: 'maa5 laai1 gou1', english: 'Malay sponge cake', measure: 'lung',
    note: 'A tall, fluffy, brown-sugar sponge cake, steamed.' },
  { id: 'pineapple-bun', hanzi: '菠蘿包', jyutping: 'bo1 lo4 baau1', english: 'pineapple bun', measure: 'dip',
    note: 'No pineapple inside! The crackly sugar top just looks like pineapple skin.' },
  { id: 'fried-rice', hanzi: '炒飯', jyutping: 'caau2 faan6', english: 'fried rice', measure: 'dip',
    note: '炒 is stir-fry. The classic has barbecued pork, shrimp, egg and spring onion.' },
  { id: 'seafood-noodles', hanzi: '海鮮炒麵', jyutping: 'hoi2 sin1 caau2 min6', english: 'seafood fried noodles', measure: 'dip',
    note: 'Crispy fried egg noodles under shrimp, squid and vegetables in a glossy sauce. 海鮮 is seafood.' },
  { id: 'beef-ho-fun', hanzi: '乾炒牛河', jyutping: 'gon1 caau2 ngau4 ho2', english: 'dry-fried beef ho fun', measure: 'dip', ssml: '乾炒牛<phoneme alphabet="sapi" ph="ho 2">河</phoneme>',
    note: 'Wide rice noodles stir-fried "dry" (乾), with no sauce, with beef and bean sprouts. 河 is usually ho4; here it changes to ho2.' },
  // phrases
  { id: 'more-water', hanzi: '唔該加水', jyutping: 'm4 goi1 gaa1 seoi2', english: 'more hot water, please', img: false,
    note: 'Or just leave the teapot lid tilted open, and staff will refill it.' },
  { id: 'bill', hanzi: '唔該埋單', jyutping: 'm4 goi1 maai4 daan1', english: 'the bill, please', img: false,
    note: 'Staff tally your order on a card stamped at each table.' },
]);

// Unit 8 · Cha Chaan Teng 茶餐廳
Words.add(8, [
  // basics
  { id: 'cha-chaan-teng', hanzi: '茶餐廳', jyutping: 'caa4 caan1 teng1', english: 'cha chaan teng (Hong Kong café)',
    note: 'Literally "tea restaurant": milk tea, toast, noodles and set meals, fast and cheap.' },
  { id: 'waiter', hanzi: '伙記', jyutping: 'fo2 gei3', english: 'waiter',
    note: 'Call out 伙記！ to get a waiter\'s attention. Also written 伙計.' },
  { id: 'jam2', hanzi: '飲', jyutping: 'jam2', english: 'to drink', img: false,
    note: 'As in 飲茶 (Unit 7): "drink tea".' },
  { id: 'sik6', hanzi: '食', jyutping: 'sik6', english: 'to eat', img: false },
  // drinks
  { id: 'milk-tea', hanzi: '奶茶', jyutping: 'naai5 caa4', english: 'milk tea', measure: 'bui',
    note: 'Strong black tea with evaporated milk, strained through a cloth "silk stocking". Hot unless you say 凍.' },
  { id: 'coffee', hanzi: '咖啡', jyutping: 'gaa3 fe1', english: 'coffee', measure: 'bui' },
  { id: 'yuenyeung', hanzi: '鴛鴦', jyutping: 'jyun1 joeng1', english: 'yuenyeung (coffee with milk tea)', measure: 'bui',
    note: 'Named after mandarin ducks, which pair for life: coffee and tea together.' },
  { id: 'lemon-tea', hanzi: '檸檬茶', jyutping: 'ning4 mung1 caa4', english: 'lemon tea', measure: 'bui',
    note: 'Often shortened to 檸茶 ning2 caa4. Iced, it comes with the lemon slices mashed in.' },
  // food
  { id: 'pineapple-butter', hanzi: '菠蘿油', jyutping: 'bo1 lo4 jau4', english: 'pineapple bun with butter', measure: 'go',
    note: 'A warm 菠蘿包 (Unit 7) cut open around a thick slab of cold butter. 油 is oil, and butter here.' },
  { id: 'spam-egg-noodles', hanzi: '餐蛋麵', jyutping: 'caan1 daan2 min6', english: 'luncheon meat and egg noodles', measure: 'wun',
    note: '餐肉 (luncheon meat) + 蛋 (egg) + 麵 (instant noodles, in soup). 蛋 is daan6, but daan2 here, as in 雞蛋.' },
  { id: 'macaroni', hanzi: '通粉', jyutping: 'tung1 fan2', english: 'macaroni (in soup)', measure: 'wun',
    note: 'Literally "through noodles": they have a hole. Usually with ham: 火腿通粉.' },
  { id: 'toast', hanzi: '多士', jyutping: 'do1 si2', english: 'toast', measure: 'fan6', phoneme: true,
    note: 'From the English "toast". Comes with butter, jam or condensed milk.' },
  { id: 'french-toast', hanzi: '西多士', jyutping: 'sai1 do1 si2', english: 'French toast', measure: 'fan6', phoneme: true,
    note: '"Western toast": deep-fried, with butter and syrup on top.' },
  // modifiers
  { id: 'dung', hanzi: '凍', jyutping: 'dung3', english: 'iced; cold', img: false,
    note: 'Goes before the drink: 凍奶茶. Iced drinks usually cost a little more.' },
  { id: 'jit', hanzi: '熱', jyutping: 'jit6', english: 'hot', img: false,
    note: 'Drinks are hot unless you ask for 凍, so 熱 is often left out.' },
  { id: 'zau', hanzi: '走', jyutping: 'zau2', english: 'without (leave out)', img: false,
    note: 'Literally "go away": 走甜 is no sugar, 走冰 no ice. Goes after the drink.' },
  { id: 'siu', hanzi: '少', jyutping: 'siu2', english: 'less; a little', img: false, phoneme: true,
    note: 'After the drink: 少甜, less sweet. Not siu3 (young).' },
  { id: 'do', hanzi: '多', jyutping: 'do1', english: 'more; a lot', img: false,
    note: 'After the drink: 多冰, extra ice.' },
  { id: 'bing', hanzi: '冰', jyutping: 'bing1', english: 'ice', img: false },
  { id: 'ding', hanzi: '定', jyutping: 'ding6', english: 'or (in a question)', img: false,
    note: 'Asks which one: 凍定熱？ Iced or hot?' },
  { id: 'gaa1', hanzi: '加', jyutping: 'gaa1', english: 'to add; extra', img: false,
    note: 'As in 唔該加水 (Unit 7). 加錢 is to pay extra.' },
  { id: 'dung-jam', hanzi: '凍飲', jyutping: 'dung3 jam2', english: 'cold drink', img: false },
  // place
  { id: 'tong-sik', hanzi: '堂食', jyutping: 'tong4 sik6', english: 'eat in', img: false,
    note: 'Literally "hall eat": eat at the table.' },
  { id: 'ling-zau', hanzi: '拎走', jyutping: 'ling1 zau2', english: 'take away', img: false,
    note: '拎 is to carry; 走 is to go, as in 走甜.' },
]);

// Unit 9 · Time & Dates 時間
Words.add(9, [
  // clock
  { id: 'dim', hanzi: '點', jyutping: 'dim2', english: 'o\'clock (hour)', img: false,
    note: 'Counts hours like a measure word: 三點, and 兩點 for two o\'clock.' },
  { id: 'zung', hanzi: '鐘', jyutping: 'zung1', english: 'clock; o\'clock',
    note: '三點鐘 is "three o\'clock"; the 鐘 is often left out.' },
  { id: 'zi6', hanzi: '字', jyutping: 'zi6', english: 'five minutes', img: false,
    note: 'Literally "character": one numeral on the clock face, so 三點兩個字 is 3:10.' },
  { id: 'fan', hanzi: '分', jyutping: 'fan1', english: 'minute', img: false,
    note: 'For exact minutes: 三點十五分. 三點三個字 is more everyday.' },
  { id: 'gei', hanzi: '幾', jyutping: 'gei2', english: 'which; how many', img: false,
    note: 'Asks for a number: 幾點 (what time), 星期幾 (what day).' },
  { id: 'gei-si', hanzi: '幾時', jyutping: 'gei2 si4', english: 'when', img: false },
  { id: 'ji-gaa', hanzi: '而家', jyutping: 'ji4 gaa1', english: 'now', img: false },
  // day
  { id: 'ziu-zou', hanzi: '朝早', jyutping: 'ziu1 zou2', english: 'morning', img: false },
  { id: 'soeng-zau', hanzi: '上晝', jyutping: 'soeng6 zau3', english: 'before noon; a.m.', img: false },
  { id: 'aan-zau', hanzi: '晏晝', jyutping: 'aan3 zau3', english: 'midday; early afternoon', img: false,
    note: 'Lunchtime. 晏 on its own means late.' },
  { id: 'haa-zau', hanzi: '下晝', jyutping: 'haa6 zau3', english: 'afternoon; p.m.', img: false },
  { id: 'je-maan', hanzi: '夜晚', jyutping: 'je6 maan5', english: 'evening; night', img: false, phoneme: true,
    note: 'Often said je6 maan1 too.' },
  { id: 'gam-ziu', hanzi: '今朝', jyutping: 'gam1 ziu1', english: 'this morning', img: false },
  { id: 'gam-maan', hanzi: '今晚', jyutping: 'gam1 maan5', english: 'tonight', img: false },
  // calendar
  { id: 'sing-kei', hanzi: '星期', jyutping: 'sing1 kei4', english: 'week; day of the week', img: false,
    note: '禮拜 lai5 baai3 means the same: 禮拜一 is Monday too.' },
  { id: 'jyut', hanzi: '月', jyutping: 'jyut6', english: 'month', img: false },
  { id: 'hou6', hanzi: '號', jyutping: 'hou6', english: 'day of the month', img: false,
    note: '三號 is the 3rd. Written dates use 日 instead.' },
  { id: 'soeng6', hanzi: '上', jyutping: 'soeng6', english: 'last (week, month)', img: false },
  { id: 'haa', hanzi: '下', jyutping: 'haa6', english: 'next (week, month)', img: false },
  // days
  { id: 'cin-jat', hanzi: '前日', jyutping: 'cin4 jat6', english: 'the day before yesterday', img: false },
  { id: 'kam-jat', hanzi: '琴日', jyutping: 'kam4 jat6', english: 'yesterday', img: false,
    note: 'Also 尋日 cam4 jat6. Low falling tone 4, unlike 今日.' },
  { id: 'gam-jat', hanzi: '今日', jyutping: 'gam1 jat6', english: 'today', img: false,
    note: 'High tone 1: 今日 gam1, but 琴日 kam4 is yesterday.' },
  { id: 'ting-jat', hanzi: '聽日', jyutping: 'ting1 jat6', english: 'tomorrow', img: false },
  { id: 'hau-jat', hanzi: '後日', jyutping: 'hau6 jat6', english: 'the day after tomorrow', img: false },
  { id: 'gam-nin', hanzi: '今年', jyutping: 'gam1 nin2', english: 'this year', img: false, voice: 'minimax:Cantonese_ProfessionalHost（F)',
    note: '年 is nin4, but changes to nin2 in 今年, 舊年 and 出年.' },
  { id: 'gau-nin', hanzi: '舊年', jyutping: 'gau6 nin2', english: 'last year', img: false, voice: 'minimax:Cantonese_ProfessionalHost（F)',
    note: 'Literally "old year".' },
  { id: 'ceot-nin', hanzi: '出年', jyutping: 'ceot1 nin2', english: 'next year', img: false, voice: 'minimax:Cantonese_ProfessionalHost（F)',
    note: 'Literally "out year". 明年 ming4 nin2 also works.' },
  // verbs
  { id: 'faan-gung', hanzi: '返工', jyutping: 'faan1 gung1', english: 'to go to work', img: false },
  { id: 'fong-gung', hanzi: '放工', jyutping: 'fong3 gung1', english: 'to finish work', img: false },
  { id: 'sik-faan', hanzi: '食飯', jyutping: 'sik6 faan6', english: 'to eat; to have a meal', img: false,
    note: 'Literally "eat rice", for any meal.' },
  { id: 'gin3', hanzi: '見', jyutping: 'gin3', english: 'to see; to meet', img: false,
    note: 'After a time, "see you then": 聽日見！' },
]);

// Unit 10 · Family 屋企人
Words.add(10, [
  // parents
  { id: 'home', hanzi: '屋企', jyutping: 'uk1 kei2', english: 'home; family',
    note: '企 is kei5 on its own, but kei2 here.' },
  { id: 'family', hanzi: '屋企人', jyutping: 'uk1 kei2 jan4', english: 'family (the people)',
    note: 'Literally "home people".' },
  { id: 'dad', hanzi: '爸爸', jyutping: 'baa4 baa1', english: 'dad; father',
    note: 'Low, then high. Casually 老豆 lou5 dau6.' },
  { id: 'mum', hanzi: '媽媽', jyutping: 'maa4 maa1', english: 'mum; mother',
    note: 'Low, then high, like 爸爸. Casually 阿媽 aa3 maa1.' },
  // siblings
  { id: 'elder-brother', hanzi: '哥哥', jyutping: 'go4 go1', english: 'older brother',
    note: 'Casually 大佬 daai6 lou2, "big guy".' },
  { id: 'elder-sister', hanzi: '家姐', jyutping: 'gaa1 ze1', english: 'older sister',
    note: '姐 is ze2 on its own, but ze1 here.' },
  { id: 'younger-brother', hanzi: '細佬', jyutping: 'sai3 lou2', english: 'younger brother',
    note: '細 is small, as in 細路 (child).' },
  { id: 'younger-sister', hanzi: '細妹', jyutping: 'sai3 mui2', english: 'younger sister',
    note: '妹 is mui6 on its own, but mui2 here.' },
  { id: 'siblings', hanzi: '兄弟姊妹', jyutping: 'hing1 dai6 zi2 mui6', english: 'brothers and sisters',
    note: 'Four words in one: older and younger brothers, older and younger sisters.' },
  // grandparents
  { id: 'dads-dad', hanzi: '爺爺', jyutping: 'je4 je2', english: 'grandpa (dad\'s dad)' },
  { id: 'dads-mum', hanzi: '嫲嫲', jyutping: 'maa4 maa4', english: 'grandma (dad\'s mum)',
    note: 'Low and falling twice, unlike 媽媽 maa4 maa1.' },
  { id: 'mums-dad', hanzi: '公公', jyutping: 'gung4 gung1', english: 'grandpa (mum\'s dad)',
    note: '公 is gung1, but the first one drops to tone 4.' },
  { id: 'mums-mum', hanzi: '婆婆', jyutping: 'po4 po2', english: 'grandma (mum\'s mum)',
    note: 'Also a polite word for any old lady.' },
  // own
  { id: 'husband', hanzi: '老公', jyutping: 'lou5 gung1', english: 'husband' },
  { id: 'wife', hanzi: '老婆', jyutping: 'lou5 po4', english: 'wife' },
  { id: 'son', hanzi: '仔', jyutping: 'zai2', english: 'son', measure: 'go',
    note: 'Counted with 個: 我個仔, my son.' },
  { id: 'daughter', hanzi: '女', jyutping: 'neoi2', english: 'daughter', measure: 'go', voice: 'minimax:Cantonese_ProfessionalHost（F)',
    note: '女 is neoi5 (female), but neoi2 for a daughter: 我個女.' },
  { id: 'children', hanzi: '仔女', jyutping: 'zai2 neoi2', english: 'children (sons and daughters)' },
  // words
  { id: 'ge', hanzi: '嘅', jyutping: 'ge3', english: '\'s; of (makes "my", "whose")', img: false,
    note: 'After a person: 我嘅書, my book. On its own at the end: 係我嘅, it\'s mine.' },
  { id: 'tung', hanzi: '同', jyutping: 'tung4', english: 'and; with', img: false,
    note: 'Joins people: 爸爸同媽媽. Before a verb it means "with": 我同佢住.' },
  { id: 'zyu', hanzi: '住', jyutping: 'zyu6', english: 'to live (somewhere)', img: false },
  { id: 'seoi', hanzi: '歲', jyutping: 'seoi3', english: 'years old', img: false,
    note: 'No 係 needed: 佢三歲, he / she is three.' },
]);

// Unit 11 · Getting Around 出街
Words.add(11, [
  // verbs
  { id: 'heoi', hanzi: '去', jyutping: 'heoi3', english: 'to go (to)', img: false,
    note: 'The place follows straight after: 去機場, go to the airport. No word for "to".' },
  { id: 'lai', hanzi: '嚟', jyutping: 'lai4', english: 'to come', img: false },
  { id: 'hai2', hanzi: '喺', jyutping: 'hai2', english: 'to be at; at', img: false,
    note: 'hai2, rising: not 係 hai6 (to be). 我喺屋企, I\'m at home.' },
  { id: 'ceot', hanzi: '出', jyutping: 'ceot1', english: 'to go out', img: false,
    note: 'As in 出口 (exit) and 出年 (next year, Unit 9).' },
  { id: 'daap', hanzi: '搭', jyutping: 'daap3', english: 'to take (a bus, the MTR)', img: false,
    note: 'For any transport: 搭巴士, 搭的士, 搭港鐵.' },
  { id: 'haang-lou', hanzi: '行路', jyutping: 'haang4 lou6', english: 'to walk', img: false,
    note: 'Literally "walk road". 行 on its own is to walk, too.' },
  { id: 'lok', hanzi: '落', jyutping: 'lok6', english: 'to get off; to go down', img: false },
  // where
  { id: 'bin-dou', hanzi: '邊度', jyutping: 'bin1 dou6', english: 'where', img: false,
    note: 'Goes where the answer goes: 你去邊度呀？ 我去機場.' },
  { id: 'dou6', hanzi: '度', jyutping: 'dou6', english: 'place (in 呢度, 嗰度)', img: false },
  { id: 'kan', hanzi: '近', jyutping: 'kan5', english: 'near; close', img: false, phoneme: true },
  { id: 'jyun', hanzi: '遠', jyutping: 'jyun5', english: 'far', img: false },
  // transport
  { id: 'metro', hanzi: '港鐵', jyutping: 'gong2 tit3', english: 'MTR (the metro)',
    note: 'Literally "Hong Kong rail". Also called 地鐵 dei6 tit3.' },
  { id: 'bus', hanzi: '巴士', jyutping: 'baa1 si2', english: 'bus', phoneme: true,
    note: 'From the English "bus". Most are double-deckers.' },
  { id: 'minibus', hanzi: '小巴', jyutping: 'siu2 baa1', english: 'minibus',
    note: 'Sixteen or so seats. Call out where you want to get off.' },
  { id: 'taxi', hanzi: '的士', jyutping: 'dik1 si2', english: 'taxi', phoneme: true,
    note: 'From the English "taxi". Hong Kong\'s city taxis are red.' },
  { id: 'tram', hanzi: '電車', jyutping: 'din6 ce1', english: 'tram',
    note: 'Literally "electric car": the narrow double-decker trams on Hong Kong Island.' },
  // places
  { id: 'zaam', hanzi: '站', jyutping: 'zaam6', english: 'station; stop', img: false },
  { id: 'toilet', hanzi: '洗手間', jyutping: 'sai2 sau2 gaan1', english: 'toilet',
    note: 'Literally "wash hands room".' },
  { id: 'bank', hanzi: '銀行', jyutping: 'ngan4 hong4', english: 'bank',
    note: '行 is hong4 here, not haang4 (walk).' },
  { id: 'hospital', hanzi: '醫院', jyutping: 'ji1 jyun2', english: 'hospital',
    note: '院 is jyun6 on its own, but jyun2 here.' },
  { id: 'supermarket', hanzi: '超市', jyutping: 'ciu1 si5', english: 'supermarket',
    note: 'Short for 超級市場, "super market".' },
  { id: 'park', hanzi: '公園', jyutping: 'gung1 jyun2', english: 'park',
    note: '園 is jyun4 on its own, but jyun2 here.' },
  { id: 'hotel', hanzi: '酒店', jyutping: 'zau2 dim3', english: 'hotel' },
  { id: 'airport', hanzi: '機場', jyutping: 'gei1 coeng4', english: 'airport',
    note: 'Literally "machine field", 機 as in 飛機.' },
  // way
  { id: 'zo', hanzi: '左', jyutping: 'zo2', english: 'left', img: false },
  { id: 'jau6', hanzi: '右', jyutping: 'jau6', english: 'right', img: false },
  { id: 'zo-bin', hanzi: '左邊', jyutping: 'zo2 bin1', english: 'the left (side)', img: false,
    note: '邊 is "side" here; in 邊度 it means "which".' },
  { id: 'jau-bin', hanzi: '右邊', jyutping: 'jau6 bin1', english: 'the right (side)', img: false },
  { id: 'zik-haang', hanzi: '直行', jyutping: 'zik6 haang4', english: 'go straight on', img: false,
    note: 'Literally "straight walk".' },
  { id: 'zyun', hanzi: '轉', jyutping: 'zyun3', english: 'to turn', img: false, phoneme: true,
    note: 'Before the direction: 轉左, turn left.' },
  { id: 'cin-min', hanzi: '前面', jyutping: 'cin4 min6', english: 'ahead; in front', img: false },
  { id: 'deoi-min', hanzi: '對面', jyutping: 'deoi3 min6', english: 'opposite; across the road', img: false },
]);

// Unit 12 · Colours & Clothes 顏色同衫
Words.add(12, [
  // basics
  { id: 'ngaan-sik', hanzi: '顏色', jyutping: 'ngaan4 sik1', english: 'colour',
    note: 'Every colour ends in 色: 紅色, 藍色.' },
  { id: 'daa-baan', hanzi: '打扮', jyutping: 'daa2 baan6', english: 'to dress up; to get ready',
    note: 'Choosing what to wear.' },
  { id: 'zoek', hanzi: '著', jyutping: 'zoek3', english: 'to wear (clothes, shoes)', img: false, phoneme: true,
    note: 'For what you put your body into: 著衫, 著褲, 著鞋.' },
  { id: 'daai', hanzi: '戴', jyutping: 'daai3', english: 'to wear (a hat, glasses)', img: false,
    note: 'For what you put on: 戴帽, 戴眼鏡, 戴手錶 (a watch).' },
  { id: 'leng', hanzi: '靚', jyutping: 'leng3', english: 'pretty; nice-looking', img: false,
    note: 'For people and things: 好靚.' },
  // colours
  { id: 'hung', hanzi: '紅色', jyutping: 'hung4 sik1', english: 'red' },
  { id: 'caang', hanzi: '橙色', jyutping: 'caang2 sik1', english: 'orange',
    note: 'The colour of 橙 (Unit 6).' },
  { id: 'wong', hanzi: '黃色', jyutping: 'wong4 sik1', english: 'yellow' },
  { id: 'luk', hanzi: '綠色', jyutping: 'luk6 sik1', english: 'green' },
  { id: 'laam', hanzi: '藍色', jyutping: 'laam4 sik1', english: 'blue' },
  { id: 'zi2', hanzi: '紫色', jyutping: 'zi2 sik1', english: 'purple' },
  { id: 'fan-hung', hanzi: '粉紅色', jyutping: 'fan2 hung4 sik1', english: 'pink',
    note: '"Powder red".' },
  { id: 'fe', hanzi: '啡色', jyutping: 'fe1 sik1', english: 'brown',
    note: 'The colour of 咖啡, coffee.' },
  { id: 'hak', hanzi: '黑色', jyutping: 'hak1 sik1', english: 'black' },
  { id: 'baak6', hanzi: '白色', jyutping: 'baak6 sik1', english: 'white' },
  { id: 'fui', hanzi: '灰色', jyutping: 'fui1 sik1', english: 'grey',
    note: '灰 is ash.' },
  // clothes
  { id: 'hat', hanzi: '帽', jyutping: 'mou2', english: 'hat; cap', measure: 'deng',
    note: 'mou2 in speech. Worn with 戴: 戴帽.' },
  { id: 'coat', hanzi: '外套', jyutping: 'ngoi6 tou3', english: 'coat; jacket', measure: 'gin',
    note: 'Literally "outer cover". A top, so 件.' },
  { id: 'skirt', hanzi: '裙', jyutping: 'kwan4', english: 'skirt; dress', measure: 'tiu',
    note: 'Long like trousers, so 條.' },
  { id: 'glasses', hanzi: '眼鏡', jyutping: 'ngaan5 geng2', english: 'glasses', measure: 'fu',
    note: '鏡 is geng3, but geng2 here. Worn with 戴.' },
  // measures
  { id: 'deng', hanzi: '頂', jyutping: 'deng2', english: 'for hats', img: false,
    note: '頂 is the top: 一頂帽.' },
  { id: 'fu', hanzi: '副', jyutping: 'fu3', english: 'a pair of (glasses)', img: false,
    note: 'For a set that goes together: 一副眼鏡.' },
]);

// Unit 13 · Weather 天氣
Words.add(13, [
  // basics
  { id: 'tin-hei', hanzi: '天氣', jyutping: 'tin1 hei3', english: 'weather',
    note: 'Literally "sky air".' },
  { id: 'tin-man-toi', hanzi: '天文台', jyutping: 'tin1 man4 toi4', english: 'the Hong Kong Observatory', img: false,
    note: 'Literally "astronomy tower": it gives the forecast and hoists the typhoon signals.' },
  { id: 'taai-joeng', hanzi: '太陽', jyutping: 'taai3 joeng4', english: 'the sun' },
  { id: 'wan', hanzi: '雲', jyutping: 'wan4', english: 'cloud' },
  { id: 'jyu', hanzi: '雨', jyutping: 'jyu5', english: 'rain', img: false },
  { id: 'syut', hanzi: '雪', jyutping: 'syut3', english: 'snow', img: false },
  { id: 'fung', hanzi: '風', jyutping: 'fung1', english: 'wind', img: false },
  { id: 'daa', hanzi: '打', jyutping: 'daa2', english: 'to hit; to strike', img: false,
    note: 'As in 打風, a typhoon "strikes".' },
  // weather
  { id: 'tin-cing', hanzi: '天晴', jyutping: 'tin1 cing4', english: 'sunny; fine',
    note: 'The sky is clear.' },
  { id: 'jam-tin', hanzi: '陰天', jyutping: 'jam1 tin1', english: 'cloudy; overcast',
    note: '陰 is shade.' },
  { id: 'daai-fung', hanzi: '大風', jyutping: 'daai6 fung1', english: 'windy; a strong wind',
    note: '"Big wind": 今日好大風, it\'s very windy today.' },
  { id: 'haang-leoi', hanzi: '行雷', jyutping: 'haang4 leoi4', english: 'to thunder; a thunderstorm',
    note: 'Literally "the thunder walks". 行 as in 行路 (Unit 11).' },
  // feel
  { id: 'nyun', hanzi: '暖', jyutping: 'nyun5', english: 'warm', img: false },
  { id: 'loeng4', hanzi: '涼', jyutping: 'loeng4', english: 'cool (pleasantly)', img: false,
    note: 'Nice and cool: 今日好涼. 沖涼 is to take a shower.' },
  { id: 'sap', hanzi: '濕', jyutping: 'sap1', english: 'damp; humid', img: false,
    note: 'In spring the walls drip: 回南天, when the south wind comes back.' },
  { id: 'gon', hanzi: '乾', jyutping: 'gon1', english: 'dry', img: false },
  // seasons
  { id: 'gwai-zit', hanzi: '季節', jyutping: 'gwai3 zit3', english: 'season' },
  { id: 'ceon-tin', hanzi: '春天', jyutping: 'ceon1 tin1', english: 'spring',
    note: 'Warm, grey and 濕: March and April.' },
  { id: 'haa-tin', hanzi: '夏天', jyutping: 'haa6 tin1', english: 'summer',
    note: 'Hot, 焗 and rainy, with typhoons: May to September.' },
  { id: 'cau-tin', hanzi: '秋天', jyutping: 'cau1 tin1', english: 'autumn',
    note: 'Sunny and dry: the best weather of the year.' },
  { id: 'dung-tin', hanzi: '冬天', jyutping: 'dung1 tin1', english: 'winter',
    note: '冬 dung1, high and level; 凍 dung3 (cold) is mid.' },
  // grammar
  { id: 'taai', hanzi: '太', jyutping: 'taai3', english: 'too (much)', img: false,
    note: 'Before an adjective: 太熱, too hot.' },
  { id: 'wui', hanzi: '會', jyutping: 'wui5', english: 'will; is going to', img: false,
    note: 'Before the verb: 聽日會落雨, it will rain tomorrow.' },
  { id: 'laa1', hanzi: '啦', jyutping: 'laa1', english: '(softens advice: go on, do)', img: false, phoneme: true,
    note: 'At the end of a suggestion: 帶遮啦！ Take an umbrella!' },
  { id: 'laa3', hanzi: '喇', jyutping: 'laa3', english: '(now; it has changed)', img: false, phoneme: true,
    note: 'Something new has happened: 落雨喇！ It\'s started raining!' },
  // things
  { id: 'umbrella', hanzi: '遮', jyutping: 'ze1', english: 'umbrella',
    note: 'For rain and for sun.' },
  { id: 'daai-bring', hanzi: '帶', jyutping: 'daai3', english: 'to bring; to take along', img: false,
    note: 'Sounds just like 戴 (wear, Unit 12).' },
]);

// Unit 14 · Body & Health 身體
Words.add(14, [
  // body
  { id: 'body', hanzi: '身體', jyutping: 'san1 tai2', english: 'body; health',
    note: 'Also your health: 身體好 is being healthy.' },
  { id: 'head', hanzi: '頭', jyutping: 'tau4', english: 'head', measure: 'go' },
  { id: 'eye', hanzi: '眼', jyutping: 'ngaan5', english: 'eye', measure: 'zek',
    note: 'As in 眼鏡, glasses (Unit 12).' },
  { id: 'ear', hanzi: '耳仔', jyutping: 'ji5 zai2', english: 'ear', measure: 'zek',
    note: '仔 makes it small and friendly, as in 雀仔 (little bird).' },
  { id: 'nose', hanzi: '鼻', jyutping: 'bei6', english: 'nose', measure: 'go',
    note: 'Also 鼻哥 bei6 go1.' },
  { id: 'mouth', hanzi: '口', jyutping: 'hau2', english: 'mouth' },
  { id: 'tooth', hanzi: '牙', jyutping: 'ngaa4', english: 'tooth; teeth', measure: 'zek' },
  { id: 'throat', hanzi: '喉嚨', jyutping: 'hau4 lung4', english: 'throat', measure: 'tiu',
    note: 'Long and thin, so 條: 我條喉嚨.' },
  { id: 'hand', hanzi: '手', jyutping: 'sau2', english: 'hand; arm', measure: 'zek',
    note: 'The whole arm, too.' },
  { id: 'foot', hanzi: '腳', jyutping: 'goek3', english: 'foot; leg', measure: 'zek',
    note: 'The whole leg, too.' },
  { id: 'stomach', hanzi: '肚', jyutping: 'tou5', english: 'stomach; belly', measure: 'go' },
  { id: 'back', hanzi: '背脊', jyutping: 'bui3 zek3', english: 'back',
    note: '脊 is zek3 in speech.' },
  // health
  { id: 'tung3', hanzi: '痛', jyutping: 'tung3', english: 'to hurt; pain', img: false,
    note: 'After the body part: 頭痛, a headache.' },
  { id: 'ji-sang', hanzi: '醫生', jyutping: 'ji1 sang1', english: 'doctor',
    note: '醫 as in 醫院, hospital (Unit 11).' },
  { id: 'tai', hanzi: '睇', jyutping: 'tai2', english: 'to look at; to see', img: false,
    note: 'Also to read or watch: 睇書, 睇戲.' },
  { id: 'joek', hanzi: '藥', jyutping: 'joek6', english: 'medicine',
    note: 'You "eat" medicine: 食藥, even a syrup.' },
  { id: 'cold', hanzi: '感冒', jyutping: 'gam2 mou6', english: 'a cold; the flu', img: false,
    note: 'Catching one takes 咗: 我感冒咗.' },
  { id: 'lau', hanzi: '流', jyutping: 'lau4', english: 'to flow; to run', img: false },
  { id: 'syu-fuk', hanzi: '舒服', jyutping: 'syu1 fuk6', english: 'comfortable; well', img: false,
    note: '唔舒服: unwell, not feeling good.' },
  { id: 'jau-sik', hanzi: '休息', jyutping: 'jau1 sik1', english: 'to rest' },
  { id: 'hou-faan', hanzi: '好返', jyutping: 'hou2 faan1', english: 'to get better', img: false, phoneme: true,
    note: '返 is "back": good again.' },
  { id: 'bou-zung', hanzi: '保重', jyutping: 'bou2 zung6', english: 'take care!', img: false },
  { id: 'zou', hanzi: '早', jyutping: 'zou2', english: 'early; soon', img: false,
    note: 'As in 早晨 (Unit 2), "early morning".' },
  // symptoms
  { id: 'fever', hanzi: '發燒', jyutping: 'faat3 siu1', english: 'to have a fever',
    note: 'Literally "put out heat".' },
  { id: 'cough', hanzi: '咳', jyutping: 'kat1', english: 'to cough',
    note: 'Also 咳嗽 kat1 sau3.' },
  // grammar
  { id: 'zo2', hanzi: '咗', jyutping: 'zo2', english: '(done; has happened)', img: false,
    note: 'Straight after the verb: 食咗藥, took the medicine.' },
  { id: 'mou', hanzi: '冇', jyutping: 'mou5', english: 'not have; there isn\'t', img: false,
    note: 'The opposite of 有. Never 唔有.' },
  { id: 'mei', hanzi: '未', jyutping: 'mei6', english: 'not yet', img: false,
    note: 'Asks "yet?" at the end: 食咗未呀？ Answers "not yet" on its own.' },
  // counting
  { id: 'jat6', hanzi: '日', jyutping: 'jat6', english: 'day (counted)', img: false,
    note: 'Counted without a measure word: 一日, 兩日.' },
  { id: 'ci', hanzi: '次', jyutping: 'ci3', english: 'time(s); occasion', img: false,
    note: 'Counts how often: 三次, three times.' },
  { id: 'nap', hanzi: '粒', jyutping: 'nap1', english: 'for pills, sweets, grains', img: false,
    note: 'A measure word for small round things: 兩粒藥.' },
  { id: 'mui', hanzi: '每', jyutping: 'mui5', english: 'every; each', img: false },
]);

// Unit 15 · Daily Routine 日常
Words.add(15, [
  // verbs
  { id: 'hei', hanzi: '起', jyutping: 'hei2', english: 'to rise; to get up', img: false },
  { id: 'caat', hanzi: '刷', jyutping: 'caat3', english: 'to brush', img: false,
    note: 'Often said caat2 too.' },
  { id: 'sai', hanzi: '洗', jyutping: 'sai2', english: 'to wash', img: false },
  { id: 'cung', hanzi: '沖', jyutping: 'cung1', english: 'to rinse; to pour water over', img: false },
  { id: 'faan', hanzi: '返', jyutping: 'faan1', english: 'to go back; to go (to work, school)', img: false, phoneme: true,
    note: 'Where you go every day: 返工, 返學, 返屋企.' },
  { id: 'fong', hanzi: '放', jyutping: 'fong3', english: 'to let go; to finish (work, school)', img: false },
  { id: 'zyu2', hanzi: '煮', jyutping: 'zyu2', english: 'to cook; to boil', img: false },
  { id: 'zou6', hanzi: '做', jyutping: 'zou6', english: 'to do; to make', img: false },
  // things
  { id: 'san', hanzi: '身', jyutping: 'san1', english: 'body', img: false,
    note: 'As in 身體 (Unit 14). 起身 is "raise the body".' },
  { id: 'min', hanzi: '面', jyutping: 'min6', english: 'face', img: false,
    note: 'Also a side, as in 前面 and 對面 (Unit 11).' },
  { id: 'gung', hanzi: '工', jyutping: 'gung1', english: 'work; a job', img: false },
  { id: 'hok', hanzi: '學', jyutping: 'hok6', english: 'school; to learn', img: false },
  { id: 'zou-caan', hanzi: '早餐', jyutping: 'zou2 caan1', english: 'breakfast', img: false,
    note: '早 is early, as in 早晨 (Unit 2).' },
  { id: 'aan', hanzi: '晏', jyutping: 'aan3', english: 'lunch (in 食晏)', img: false,
    note: '晏 is midday, as in 晏晝 (Unit 9).' },
  { id: 'maan-faan', hanzi: '晚飯', jyutping: 'maan5 faan6', english: 'dinner', img: false },
  { id: 'din-si', hanzi: '電視', jyutping: 'din6 si6', english: 'television', img: false,
    note: '電 is electric, as in 電車 (Unit 11).' },
  { id: 'gaau', hanzi: '覺', jyutping: 'gaau3', english: 'a sleep', img: false,
    note: 'Read gaau3 in 瞓覺, but gok3 in 感覺 (a feeling).' },
  { id: 'je', hanzi: '嘢', jyutping: 'je5', english: 'things; stuff', img: false,
    note: 'As in 乜嘢 (Unit 3). 做嘢 is "do things": to work.' },
  // grammar
  { id: 'gan', hanzi: '緊', jyutping: 'gan2', english: '(-ing; happening now)', img: false,
    note: 'Straight after the verb, like 咗: 食緊飯, eating.' },
  { id: 'gwo', hanzi: '過', jyutping: 'gwo3', english: '(ever; have done before)', img: false,
    note: 'Straight after the verb: 去過, have been.' },
  // order
  { id: 'tung-soeng', hanzi: '通常', jyutping: 'tung1 soeng4', english: 'usually', img: false },
  { id: 'sin', hanzi: '先', jyutping: 'sin1', english: 'first', img: false,
    note: 'Before the verb: 我先刷牙.' },
  { id: 'jin-hau', hanzi: '然後', jyutping: 'jin4 hau6', english: 'then; after that', img: false },
  { id: 'zi-cin', hanzi: '之前', jyutping: 'zi1 cin4', english: 'before', img: false,
    note: 'After what it is before: 瞓覺之前, before bed.' },
  { id: 'zi-hau', hanzi: '之後', jyutping: 'zi1 hau6', english: 'after', img: false,
    note: 'After what it is after: 放工之後, after work.' },
]);
